server:
  port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: bankapigateway
  cloud:
    gateway:
      routes:
      - id: profileserver
        uri: http://localhost:8081/
        predicates:
        - Path=/profile/**
      - id: transactionserver
        uri: http://localhost:8082/
        predicates:
        - Path=/transaction/**
      - id: aggregatorserver
        uri: http://localhost:8083/
        predicates:
        - Path=/aggregator/**